// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy8xgRNZIJoAxDZrPB2HEt2nBH8b31Zx0',
    appId: '1:346806222390:web:5e4f1f8cfc403230f16297',
    messagingSenderId: '346806222390',
    projectId: 'one-signal-d7563',
    authDomain: 'one-signal-d7563.firebaseapp.com',
    storageBucket: 'one-signal-d7563.appspot.com',
    measurementId: 'G-2QCCNVDWQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBnD_F4Uw7xbVPOVcA7R5ugycnHsx_NWw',
    appId: '1:346806222390:android:441673cc1a48a897f16297',
    messagingSenderId: '346806222390',
    projectId: 'one-signal-d7563',
    storageBucket: 'one-signal-d7563.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW4aQ0Cclgn87_DrRTwHoQwZ01z5ViTng',
    appId: '1:346806222390:ios:3e03e5fd7a74ca44f16297',
    messagingSenderId: '346806222390',
    projectId: 'one-signal-d7563',
    storageBucket: 'one-signal-d7563.appspot.com',
    iosBundleId: 'com.example.graduateProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW4aQ0Cclgn87_DrRTwHoQwZ01z5ViTng',
    appId: '1:346806222390:ios:3e03e5fd7a74ca44f16297',
    messagingSenderId: '346806222390',
    projectId: 'one-signal-d7563',
    storageBucket: 'one-signal-d7563.appspot.com',
    iosBundleId: 'com.example.graduateProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy8xgRNZIJoAxDZrPB2HEt2nBH8b31Zx0',
    appId: '1:346806222390:web:448b529ffdacd56bf16297',
    messagingSenderId: '346806222390',
    projectId: 'one-signal-d7563',
    authDomain: 'one-signal-d7563.firebaseapp.com',
    storageBucket: 'one-signal-d7563.appspot.com',
    measurementId: 'G-14BN80008K',
  );
}
